<div id="dialog-popup"></div>
<div id="dialog-help" title="Help" style="display: none">
  <div id="helpText">
  </div>
</div>

<div id="footer" style="text-align:center;">
<br />
  <div id="rebootShutdown" class="btn-group" role="group" style="display:inline;">
      <button id="btnReboot" class="btn btn-primary btn-sm" onClick="RebootPi();">Reboot
      </button><button id="btnShutdown"  class="btn btn-primary btn-sm" onClick="ShutdownPi();">Shutdown
      </button><button id="btnRestartFPPD" class="btn btn-primary btn-sm" onClick="ClearRestartFlag();RestartFPPD();">Restart FPPD
      </button>
  </div>
<br />

</div>
</div>

<div style="text-align:center;">
<br/>
<a href="http://www.falconchristmas.com">www.falconchristmas.com</a>
<br/><br/>
</div>